### ISSUE TITLE
Not seeing traces as expected following quickstart

### ISSUE THREAD

**Issue by stianlagstad** [kamon-io/kamon-zipkin#8]
I'm following this guide: https://kamon.io/documentation/1.x/recipes/monitoring-akka-quickstart/
This is the code I've ended up with: https://github.com/stianlagstad/akka-kamon-quickstart

I start the application with `./sbt` and then `reStart`. The log output is as expected, but I don't get the zipkin traces I'd expect.

I've started zipkin with `docker run -d -p 9411:9411 openzipkin/zipkin`. I'd expect traces to be available in http://localhost:9411/zipkin/, but I don't see anything there.

At http://localhost:9095/ I see this:
```
# TYPE tracer_spans_created_total counter
tracer_spans_created_total 205.0
# TYPE span_processing_time_seconds histogram
span_processing_time_seconds_bucket{operation="randomGreeter",error="false",le="0.005"} 0.0
span_processing_time_seconds_bucket{operation="randomGreeter",error="false",le="0.01"} 0.0
span_processing_time_seconds_bucket{operation="randomGreeter",error="false",le="0.025"} 0.0
span_processing_time_seconds_bucket{operation="randomGreeter",error="false",le="0.05"} 0.0
span_processing_time_seconds_bucket{operation="randomGreeter",error="false",le="0.075"} 0.0
span_processing_time_seconds_bucket{operation="randomGreeter",error="false",le="0.1"} 0.0
span_processing_time_seconds_bucket{operation="randomGreeter",error="false",le="0.25"} 0.0
span_processing_time_seconds_bucket{operation="randomGreeter",error="false",le="0.5"} 0.0
span_processing_time_seconds_bucket{operation="randomGreeter",error="false",le="0.75"} 0.0
span_processing_time_seconds_bucket{operation="randomGreeter",error="false",le="1.0"} 203.0
span_processing_time_seconds_bucket{operation="randomGreeter",error="false",le="2.5"} 204.0
span_processing_time_seconds_bucket{operation="randomGreeter",error="false",le="5.0"} 204.0
span_processing_time_seconds_bucket{operation="randomGreeter",error="false",le="7.5"} 204.0
span_processing_time_seconds_bucket{operation="randomGreeter",error="false",le="10.0"} 204.0
span_processing_time_seconds_bucket{operation="randomGreeter",error="false",le="+Inf"} 204.0
span_processing_time_seconds_count{operation="randomGreeter",error="false"} 204.0
span_processing_time_seconds_sum{operation="randomGreeter",error="false"} 203.650236416
```

I'm still new to both akka and tracing, so hopefully there's something obvious I've missed. Could you please take a look? Thank you!

**Comment by stianlagstad** [comment]
A good colleague of mine, @wjoel, found the solution to this. I had to add another configuration parameter: `kamon.trace.sampler = "always"`. [This change](https://github.com/stianlagstad/akka-kamon-quickstart/commit/b90367422894e9d0506f956e003a2f78a47c542c) made traces appear in Zipkin:
![screenshot from 2019-02-16 14-42-10](https://user-images.githubusercontent.com/4340859/52900691-1296c800-31f9-11e9-9497-34c835659a0b.png)

**Comment by jatcwang** [comment]
Can this be closed @stianlagstad?

**Comment by stianlagstad** [comment]
Yes.
